---
title: "Plopper"
author: "Alexandra Vajda"
date: "22/05/2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r}
mydata <- read.csv(file = "3.1.txt", sep = ",", header = TRUE)
dim(mydata)
str(mydata)
```
```{r}
mydata [1:20, ]
```
```{r}
hist(mydata$score, xlim = c(0,80))
```
```{r}
summary(mydata)
summary(mydata$score)

sd(mydata$score)
```
```{r}
hist(mydata$cohort90, xlim = c(-6, 8))
```
```{r}
mydata <- read.csv("3.1.txt", sep = ",", header = TRUE)

mytable <- table(mydata$cohort90)
mytable
```
```{r}
prop.table(mytable)
```
```{r}
mytablecomb <- cbind(mytable, prop.table(mytable), cumsum(prop.table(mytable)))
mytablecomb

```

```{r}
colnames(mytablecomb) <- c("Freq", "Perc", "Cum")
mytablecomb
```
```{r}
mytablecomb
```
```{r}
plot(mydata$cohort90, mydata$score, ylim = c(0,80))
```
#Tapply command applies a function to each group of values given by the levels of the specified factor.
#The first line calculates the lenght of score for each value of cohort90, providing the number of observations for each level of cohort90.
```{r}
l <- tapply(mydata$score, factor(mydata$cohort90), length)
m <- tapply(mydata$score, factor(mydata$cohort90), mean)
s <- tapply(mydata$score, factor(mydata$cohort90), sd)
tableScore <- cbind("Freq" = l, "mean(score)"= m, "sd(score)" = s)
```

